title: Spotlight Rules
theme: null
description: The rules to govern and provide guardrails.
lang: en

baseurl: ""

# Permalink URLs structure, for permalink style options see: https://jekyllrb.com/docs/permalinks/
permalink: /:categories/:year/:month/:day/:title/

url: "https://spotlight-rules.com"

logo: https://kinlane-images.s3.amazonaws.com/shared/api-evangelist-logos/api-evangelist-logo-butterfly.png

navbar:
    sticky:         true
    search:         true
  
author:
    name:           Kin Lane
    title:          API Evangelist
    avatar:         https://kinlane-images.s3.amazonaws.com/shared/kin-lane-cartoon-questioning.png

authors:
    kin:
      name:         Kin Lane
      title:        API Evangelist
      avatar:       https://kinlane-images.s3.amazonaws.com/shared/kin-lane-cartoon-questioning.png
      email:       'kinlane@postman.com'
      affiliation: 'API Evangelist'
      github:      'kinlane'
      linkedin:    'in/kinlane'       

social:
    email:
    website:
    facebook:       
    flickr:
    dribbble:
    github:         https://github.com/api-evangelist
    googleplus:
    instagram:     
    linkedin:       https://www.linkedin.com/in/kinlane/
    pinterest:
    twitter:        
    vimeo:          
    youtube:        https://www.youtube.com/c/KinLane
    mastodon:       

# Share button
share:
    post:           true # Display share buttons on a post page
    doc:            true # Display share buttons on a doc page
    twitter:        username # Enable by adding Twitter handle 
    facebook:       true # Enable by setting true (Facebook handle not required)

# Default footer image settings
footer:
    copyright:      API Evangelist

# Path to post content assets directory i.e post images, pdfs etc
uploads:            /uploads/

# Build settings
markdown:           kramdown
highlighter:        rouge

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-avatar
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  
sass:
  style: compressed

# Site-wide alert banner
alert:
    enabled:        false
    type:           danger # light, danger, warning, success
    message:        'Have more questions after this post? <a href="https://apievangelist.com/contact/">Let us Know!</a>'
